<?php
//inputのnameとその名称設定
//'name'=>'名称'で１セット。一番最後には,をつけない。
//ここで書いた並び順が、確認画面と送信メール本文に反映される。
$inputs = array(
	'q'=>'お問い合わせ種別',	
	'name'=>'氏名',
	'name2'=>'ふりがな',
	'birth'=>'生年月日',
	'sex'=>'性別',
	'email'=>'E-Mail',
	'postcode'=>'郵便番号',
	'address'=>'住所',
	'tel'=>'電話番号',
	'tel2'=>'FAX番号',
	'tel3'=>'携帯番号',
	'businesspost'=>'URL',
	'schoolcareer'=>'希望時間',
	'message'=>'お問い合わせ内容',
	'cont'=>'ご連絡方法',
	'time'=>'ご連絡希望時間',
	'tmpfile'=>'添付ファイル',
	'tmpfile2'=>'添付ファイル2'
);
?>